"""

Revision ID: 14da7a9ecff2
Revises: 97ec573d3a8e
Create Date: 2025-11-19 22:29:56.777557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from src import db

# revision identifiers, used by Alembic.
revision: str = '14da7a9ecff2'
down_revision: Union[str, Sequence[str], None] = '97ec573d3a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_prompts',
    sa.Column('key', postgresql.ENUM('INITIAL_REPLY', 'FOLLOWUP_REPLY', 'CLASSIFICATION', name='llm_prompt_key_enum'), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('updated_at', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key', 'brand_id')
    )
    op.create_table('llm_runtime_settings',
    sa.Column('key', postgresql.ENUM('CLASSIFICATION', 'RESPONSE', name='llm_settings_key_enum'), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.add_column('our_posts', sa.Column('body', sa.Text(), nullable=False))
    op.alter_column('telegram_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=db.models.UTCDateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('telegram_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=db.models.UTCDateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'telegram_users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_users', type_='unique')
    op.alter_column('telegram_users', 'updated_at',
               existing_type=db.models.UTCDateTime(timezone=True),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('telegram_users', 'created_at',
               existing_type=db.models.UTCDateTime(timezone=True),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('our_posts', 'body')
    op.drop_table('llm_runtime_settings')
    op.drop_table('llm_prompts')
    # ### end Alembic commands ###
