"""

Revision ID: 2477e58084e8
Revises:
Create Date: 2025-11-14 15:27:53.031154

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from src import db, datetime_utils

# revision identifiers, used by Alembic.
revision: str = '2477e58084e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('value', db.models.UTCDateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', db.models.UTCDateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('name')
                    )
    op.create_table('locks',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('holder', sa.String(), nullable=True),
                    sa.Column('until', db.models.UTCDateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('name')
                    )
    op.create_index('idx_locks_until', 'locks', ['until'], unique=False)
    op.create_table('tickets',
                    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
                    sa.Column('brand_id', sa.BigInteger(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('updated_at', db.models.UTCDateTime(timezone=True), nullable=False),
                    sa.Column('observing', sa.Boolean(), nullable=False),
                    sa.Column('last_seen_at', db.models.UTCDateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('ticket_id')
                    )
    op.create_index('idx_tickets_brand_status', 'tickets', ['brand_id', 'status', 'updated_at'], unique=False)
    op.create_table('tickets_filter_rules',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('kind', sa.String(length=50), nullable=False),
                    sa.Column('value', sa.String(length=128), nullable=False),
                    sa.Column('is_regex', sa.Boolean(), nullable=False),
                    sa.Column('brand_id', sa.BigInteger(), nullable=True),
                    sa.Column('via_channel', sa.String(length=32), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('comment', sa.Text(), nullable=True),
                    sa.Column('created_by', sa.String(length=64), nullable=True),
                    sa.Column('updated_by', sa.String(length=64), nullable=True),
                    sa.Column('created_at', db.models.UTCDateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', db.models.UTCDateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_service_filter_rules_kind_brand_channel', 'tickets_filter_rules',
                    ['kind', 'brand_id', 'via_channel', 'is_active'], unique=False)
    op.create_table('events',
                    sa.Column('event_key', sa.String(length=32), nullable=False),
                    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
                    sa.Column('source_type', sa.String(), nullable=False),
                    sa.Column('source_id', sa.String(), nullable=False),
                    sa.Column('kind', sa.String(), nullable=False),
                    sa.Column('author_role', sa.String(), nullable=True),
                    sa.Column('author_id', sa.BigInteger(), nullable=True),
                    sa.Column('is_private', sa.Boolean(), nullable=False),
                    sa.Column('has_robot_tag', sa.Boolean(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('body_hash', sa.String(length=32), nullable=True),
                    sa.Column('created_at', db.models.UTCDateTime(timezone=True), nullable=False),
                    sa.Column('inserted_at', db.models.UTCDateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('event_key')
                    )
    op.create_index('idx_events_kind_on_ticket', 'events', ['ticket_id', 'kind', 'created_at'], unique=False)
    op.create_index('idx_events_robot_on_ticket', 'events', ['ticket_id', 'has_robot_tag', 'is_private', 'created_at'],
                    unique=False)
    op.create_index('idx_events_ticket_created', 'events', ['ticket_id', 'created_at'], unique=False)
    op.create_table('our_posts',
                    sa.Column('post_key', sa.String(), nullable=False),
                    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
                    sa.Column('body_hash', sa.String(length=32), nullable=False),
                    sa.Column('channel', sa.String(), nullable=True),
                    sa.Column('created_at', db.models.UTCDateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('post_key')
                    )
    op.create_index('idx_our_posts_ticket', 'our_posts', ['ticket_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
    tickets_filter_rules = sa.table(
        "tickets_filter_rules",
        sa.column("kind", sa.String),
        sa.column("value", sa.String),
        sa.column("is_regex", sa.Boolean),
        sa.column("brand_id", sa.Integer),
        sa.column("via_channel", sa.String),
        sa.column("is_active", sa.Boolean),
        sa.column("comment", sa.Text),
        sa.column("created_by", sa.String),
        sa.column("updated_by", sa.String),
        sa.column("created_at", db.models.UTCDateTime(timezone=True)),
        sa.column("updated_at", db.models.UTCDateTime(timezone=True)),
    )
    now = datetime_utils.utcnow()
    seed_user = "alembic_seed_initial_rules"

    rows: list[dict] = []

    # --- SYSTEM_DOMAIN ---
    system_domains = {
        "1ecommerceagency.net",
        "account.tiktok.com",
        "accounts.google.com",
        "amazon.co.uk",
        "amazon.com",
        "amazonservices.com",
        "aresprojectslabs.com",
        "avedaayur.com",
        "boots.co.uk",
        "brandbuddyecomboost.com",
        "branwell.com",
        "china-msm.com",
        "chinahealthsource.com",
        "cleocora.com",
        "creatorcore.agency",
        "dailyproductspro.com",
        "dhl.com",
        "divinehealslondon.com",
        "divinepremier.co.uk",
        "ecomaresprojects.com",
        "ebay.co.uk",
        "ebay.com",
        "email1.hsbc.co.uk",
        "evri.com",
        "facebookmail.com",
        "goaresprojects.com",
        "google.com",
        "hermesworld.com",
        "hiaresprojects.com",
        "huayuantoystrading.com",
        "ingredients4u.com",
        "info.ebay.co.uk",
        "information.ebay.co.uk",
        "instagram.com",
        "insengroup.com",
        "klaviyo.com",
        "mail.boots.com",
        "mantle.boldcommerce.com",
        "marketplace.amazon.com",
        "marketplacegeek.com",
        "medikonda.com",
        "merchant-center-noreply.google.com",
        "meta.com",
        "nrbrandscaling.com",
        "novelnutrient.com",
        "nutriavenue.com",
        "oemaresprojects.com",
        "onbuy-sellers.co.uk",
        "organic-service.com",
        "paypal.co.uk",
        "paypal.com",
        "peoplespartnership.co.uk",
        "post.xero.com",
        "presidiocreative.com",
        "rapidsearch.app",
        "royalmail.com",
        "scaleforte.blog",
        "sellercentral-europe.amazon.com",
        "sellercentral.amazon.com",
        "shop.tiktok.com",
        "shopify.com",
        "shopifyemail.com",
        "shopifyintel.com",
        "smart-parts.net",
        "st.lb.edu.vn",
        "superself.io",
        "support.facebook.com",
        "taxually.com",
        "third-tree.com",
        "ukb2c.email",
        "vitajoygroup.com",
        "vitasynth.eu",
        "worten.pt",
        "xero.com",
    }

    for v in sorted(system_domains):
        rows.append(
            {
                "kind": "system_domain",
                "value": v.lower(),
                "is_regex": False,
                "brand_id": None,
                "via_channel": None,
                "is_active": True,
                "comment": "initial seed: system domain",
                "created_by": seed_user,
                "updated_by": seed_user,
                "created_at": now,
                "updated_at": now,
            }
        )

    # --- SYSTEM_ADDRESS ---
    system_addresses = {
        "donotreply@amazon.com",
        "no-reply@amazon.co.uk",
        "ebay@ebay.com",
        "no-reply@accounts.google.com",
        "googlemerchantcenter-noreply@google.com",
        "merchant-center-noreply@google.com",
        "mailer-daemon@googlemail.com",
        "postmaster@ukb2c.email",
        "mailer@shopify.com",
        "no-reply@mailer.taxually.com",
        "support@taxually.com",
        "hello@taxually.com",
        "do-not-reply@evri.com",
        "noreply@royalmail.com",
        "sellercentral-europe@amazon.com",
        "merch.service05@amazon.com",
        "merch.service05@amazon.co.uk",
        "removals@amazon.com",
        "food-supplements-approval@amazon.co.uk",
    }

    for v in sorted(system_addresses):
        rows.append(
            {
                "kind": "system_address",
                "value": v.lower(),
                "is_regex": False,
                "brand_id": None,
                "via_channel": None,
                "is_active": True,
                "comment": "initial seed: system address",
                "created_by": seed_user,
                "updated_by": seed_user,
                "created_at": now,
                "updated_at": now,
            }
        )

    # --- ADDRESS_HINT ---
    address_hints = {
        "no-reply",
        "noreply",
        "do-not-reply",
        "donotreply",
        "notification",
        "mailer",
        "daemon",
        "postmaster",
        "robot",
        "nobot",
    }

    for v in sorted(address_hints):
        rows.append(
            {
                "kind": "address_hint",
                "value": v.lower(),
                "is_regex": False,
                "brand_id": None,
                "via_channel": None,
                "is_active": True,
                "comment": "initial seed: address hint",
                "created_by": seed_user,
                "updated_by": seed_user,
                "created_at": now,
                "updated_at": now,
            }
        )

    # --- SUBJECT_PATTERN (regex) ---
    subject_patterns = [
        r"\bauto[- ]?reply\b",
        r"\bout of office\b",
        r"\balert\b",
        r"boosting visibility",
        r"check your savings",
        r"confirm a xero login",
        r"delivery status notification",
        r"feedback",
        r"^fwd:\s*veeqo:",
        r"is available\.? please update",
        r"mail delivery failed",
        r"new login from your xero account\b.*",
        r"newsletter",
        r"notification",
        r"please update",
        r"prepare for the holidays",
        r"refund offer\b.*\border id\b",
        r"run your business from anywhere",
        r"survey",
        r"the people[’']s pension\b.*\bmonthly\b.*\bthank you for your submission\b",
        r"undeliverable",
        r"updates to the ebay user agreement",
        r"your credit card\b.*\bcharged",
        r"your hsbc uk account statement is available to view",
        r"\b\d{4,8}\b\s+is your code to log in\b.*",
        r"\b\d{4,8}\b\s+is your verification code\b",
    ]

    for pat in subject_patterns:
        rows.append(
            {
                "kind": "subject_pattern",
                "value": pat,
                "is_regex": True,
                "brand_id": None,
                "via_channel": None,
                "is_active": True,
                "comment": "initial seed: subject pattern",
                "created_by": seed_user,
                "updated_by": seed_user,
                "created_at": now,
                "updated_at": now,
            }
        )

    # --- SERVICE_TAG_EXACT ---
    service_tags_exact = {
        "servicemessage",
        "system_email_notification_failure",
    }

    for v in sorted(service_tags_exact):
        rows.append(
            {
                "kind": "service_tag_exact",
                "value": v.lower(),
                "is_regex": False,
                "brand_id": None,
                "via_channel": None,
                "is_active": True,
                "comment": "initial seed: exact service tag",
                "created_by": seed_user,
                "updated_by": seed_user,
                "created_at": now,
                "updated_at": now,
            }
        )

    # --- SERVICE_TAG_PREFIX ---
    service_tag_prefixes = {
        "forward_to_",
    }

    for v in sorted(service_tag_prefixes):
        rows.append(
            {
                "kind": "service_tag_prefix",
                "value": v.lower(),
                "is_regex": False,
                "brand_id": None,
                "via_channel": None,
                "is_active": True,
                "comment": "initial seed: service tag prefix",
                "created_by": seed_user,
                "updated_by": seed_user,
                "created_at": now,
                "updated_at": now,
            }
        )

    # --- PLATFORM_TAG_HINT ---
    platform_tag_hints = {
        "amazon",
        "ebay",
        "shopify",
        "tiktok",
        "cleocora_",
        "smartparts_",
        "superself_",
    }

    for v in sorted(platform_tag_hints):
        rows.append(
            {
                "kind": "platform_tag_hint",
                "value": v.lower(),
                "is_regex": False,
                "brand_id": None,
                "via_channel": None,
                "is_active": True,
                "comment": "initial seed: platform tag hint",
                "created_by": seed_user,
                "updated_by": seed_user,
                "created_at": now,
                "updated_at": now,
            }
        )

    # --- API_ALLOWED_PATTERN (regex) ---
    api_allowed_patterns = [
        r"^new customer message on\b",
        r".*\bthe buyer sent you a message\b",
        r".*\bsent a message about\b",
        r".*\bsent you a message\b",
        r"^a new message from tiktok shop customer\b",
    ]

    for pat in api_allowed_patterns:
        rows.append(
            {
                "kind": "api_allowed_pattern",
                "value": pat,
                "is_regex": True,
                "brand_id": None,
                "via_channel": None,
                "is_active": True,
                "comment": "initial seed: api allowed pattern",
                "created_by": seed_user,
                "updated_by": seed_user,
                "created_at": now,
                "updated_at": now,
            }
        )

    # --- SPAM_SUBJECT_PATTERN (regex) ---
    spam_subject_patterns = [
        r"\bad campaign\b",
        r"\bads\b",
        r"\badvertising\b",
        r"\bagency\b",
        r"\bbacklinks?\b",
        r"\bblack friday\b",
        r"\bboost your\b",
        r"\bbulk softgel\b",
        r"\bbulk softgels\b",
        r"\bbusiness proposal\b",
        r"\bcollaboration\b",
        r"\bcontract manufacturer\b",
        r"\bcrypto\b",
        r"\bfmcg\b",
        r"\bfunding\b",
        r"\bguest post\b",
        r"\bingredients catalog\b",
        r"\bin stock for\b",
        r"\binvestment\b",
        r"\blead generation\b",
        r"\bqualified leads\b",
        r"\bleads\b",
        r"\bmarketing\b",
        r"\boem production\b",
        r"\boem service\b",
        r"\boem services\b",
        r"\boffer for\b",
        r"\bpartnership opportunity\b",
        r"\bpcs in stock\b",
        r"\bplant extract\b",
        r"\bprice list\b",
        r"\bprivate label\b",
        r"\bproposal\b",
        r"\bquotation\b",
        r"\bseo\b",
        r"\bsourcing\b",
        r"\bsponsored\b",
        r"\bsupply you\b",
        r"\btraffic growth\b",
        r"\bupgrade your website\b",
        r"\bweb design\b",
        r"\bwebinar\b",
        r"\bwhite label\b",
        r"\bwholesale\b",
        r"instagram engagement",
        r"instagram growth",
        r"\bgrow your instagram\b",
        r"\btiktok scaling\b",
        r"your brand stood out to me",
        r"boost shopify sales",
        r"scale your brand on amazon",
    ]

    for pat in spam_subject_patterns:
        rows.append(
            {
                "kind": "spam_subject_pattern",
                "value": pat,
                "is_regex": True,
                "brand_id": None,  # или нужный brand, если хочешь тонкую настройку
                "via_channel": "email",
                "is_active": True,
                "comment": "initial seed: spam subject pattern",
                "created_by": seed_user,
                "updated_by": seed_user,
                "created_at": now,
                "updated_at": now,
            }
        )

    if rows:
        op.bulk_insert(tickets_filter_rules, rows)


def downgrade() -> None:
    op.execute(
        sa.text(
            "DELETE FROM tickets_filter_rules "
            "WHERE created_by = :seed_user"
        ),
        {"seed_user": "alembic_seed_initial_rules"},
    )
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_our_posts_ticket', table_name='our_posts')
    op.drop_table('our_posts')
    op.drop_index('idx_events_ticket_created', table_name='events')
    op.drop_index('idx_events_robot_on_ticket', table_name='events')
    op.drop_index('idx_events_kind_on_ticket', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_service_filter_rules_kind_brand_channel', table_name='tickets_filter_rules')
    op.drop_table('tickets_filter_rules')
    op.drop_index('idx_tickets_brand_status', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('idx_locks_until', table_name='locks')
    op.drop_table('locks')
    op.drop_table('checkpoints')
    # ### end Alembic commands ###
