"""

Revision ID: 715e87b2f54b
Revises: 13053536ca78
Create Date: 2025-12-07 12:45:14.191893

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from src import db

# revision identifiers, used by Alembic.
revision: str = '715e87b2f54b'
down_revision: Union[str, Sequence[str], None] = '13053536ca78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'zendesk_runtime_settings',
        sa.Column('key', sa.String(length=32), nullable=False),
        sa.Column('review_channel', postgresql.ENUM('INTERNAL', 'PUBLIC', name='post_channel_enum'), nullable=False),
        sa.Column('updated_by', sa.String(length=32), nullable=True),
        sa.Column('updated_at', db.models.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('key')
    )
    op.alter_column(
        'our_posts',
        'channel',
        existing_type=sa.VARCHAR(),
        type_=postgresql.ENUM('INTERNAL', 'PUBLIC', name='post_channel_enum'),
        postgresql_using="channel::post_channel_enum",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'our_posts',
        'channel',
        existing_type=postgresql.ENUM('INTERNAL', 'PUBLIC', name='post_channel_enum'),
        type_=sa.VARCHAR(),
        postgresql_using="channel::text",
        nullable=True,
    )
    op.drop_table('zendesk_runtime_settings')
    # ### end Alembic commands ###
