"""add ticket reply attempts

Revision ID: 85ae46f57bcf
Revises: 9fd13967f3ff
Create Date: 2026-04-15 19:25:22.738709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from src import db

# revision identifiers, used by Alembic.
revision: str = '85ae46f57bcf'
down_revision: Union[str, Sequence[str], None] = '9fd13967f3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_reply_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column(
        'channel',
        postgresql.ENUM(
            'INTERNAL',
            'PUBLIC',
            name='post_channel_enum',
            create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('status', postgresql.ENUM('GENERATED', 'POSTED', 'FAILED', 'SKIPPED_DUPLICATE', 'EMPTY_REPLY', name='reply_attempt_status_enum'), nullable=False),
    sa.Column('body_hash', sa.String(length=32), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('zendesk_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_key', sa.String(length=64), nullable=True),
    sa.Column('iteration_id', sa.String(length=16), nullable=True),
    sa.Column('created_at', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('posted_at', db.models.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reply_attempts_brand_created', 'ticket_reply_attempts', ['brand_id', 'created_at'], unique=False)
    op.create_index('idx_reply_attempts_status_created', 'ticket_reply_attempts', ['status', 'created_at'], unique=False)
    op.create_index('idx_reply_attempts_ticket_created', 'ticket_reply_attempts', ['ticket_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reply_attempts_ticket_created', table_name='ticket_reply_attempts')
    op.drop_index('idx_reply_attempts_status_created', table_name='ticket_reply_attempts')
    op.drop_index('idx_reply_attempts_brand_created', table_name='ticket_reply_attempts')
    op.drop_table('ticket_reply_attempts')
    op.execute("DROP TYPE reply_attempt_status_enum")
    # ### end Alembic commands ###
