"""

Revision ID: 87397cb2ea37
Revises: 14da7a9ecff2
Create Date: 2025-11-22 16:33:47.366844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import vector
from src import db


# revision identifiers, used by Alembic.
revision: str = '87397cb2ea37'
down_revision: Union[str, Sequence[str], None] = '14da7a9ecff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=False),
    sa.Column('marketplace_id', sa.String(length=20), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('seller_sku', sa.String(length=128), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('fulfillment_channel', sa.String(length=32), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('embedding', vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'marketplace_id', 'asin', 'seller_sku', name='uq_merchant_listings_brand_marketplace_asin_sku')
    )
    op.create_index(op.f('ix_merchant_listings_brand_id'), 'merchant_listings', ['brand_id'], unique=False)
    op.create_index('ix_merchant_listings_brand_marketplace_asin', 'merchant_listings', ['brand_id', 'marketplace_id', 'asin'], unique=False)
    op.create_index('ix_merchant_listings_brand_marketplace_sku', 'merchant_listings', ['brand_id', 'marketplace_id', 'seller_sku'], unique=False)
    op.create_index(op.f('ix_merchant_listings_marketplace_id'), 'merchant_listings', ['marketplace_id'], unique=False)
    # ### end Alembic commands ###
    op.execute("""
        CREATE INDEX ix_merchant_listings_embedding
        ON merchant_listings
        USING ivfflat (embedding vector_cosine_ops)
        WITH (lists = 100);
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_merchant_listings_embedding;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_listings_marketplace_id'), table_name='merchant_listings')
    op.drop_index('ix_merchant_listings_brand_marketplace_sku', table_name='merchant_listings')
    op.drop_index('ix_merchant_listings_brand_marketplace_asin', table_name='merchant_listings')
    op.drop_index(op.f('ix_merchant_listings_brand_id'), table_name='merchant_listings')
    op.drop_table('merchant_listings')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector;")
