"""add admin users

Revision ID: 9fd13967f3ff
Revises: 715e87b2f54b
Create Date: 2026-04-15 14:56:02.139011

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from src import db

# revision identifiers, used by Alembic.
revision: str = '9fd13967f3ff'
down_revision: str | Sequence[str] | None = '715e87b2f54b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'admin_users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(length=64), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column(
            'role',
            postgresql.ENUM(
                'SUPERADMIN',
                'ADMIN',
                'USER',
                'ANONYMOUS',
                name='user_role_enum',
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', db.models.UTCDateTime(timezone=True), nullable=False),
        sa.Column('updated_at', db.models.UTCDateTime(timezone=True), nullable=False),
        sa.Column('last_login_at', db.models.UTCDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_users')
    # ### end Alembic commands ###
