"""

Revision ID: b4725cea69cf
Revises:
Create Date: 2025-10-23 11:46:00.609311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import db


# revision identifiers, used by Alembic.
revision: str = 'b4725cea69cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('locks',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('holder', sa.String(), nullable=True),
    sa.Column('until', db.models.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index('idx_locks_until', 'locks', ['until'], unique=False)
    op.create_table('tickets',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('observing', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', db.models.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index('idx_tickets_brand_status', 'tickets', ['brand_id', 'status', 'updated_at'], unique=False)
    op.create_table('events',
    sa.Column('event_key', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('author_role', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('has_robot_tag', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_hash', sa.String(), nullable=True),
    sa.Column('created_at', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('inserted_at', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_key')
    )
    op.create_index('idx_events_kind_on_ticket', 'events', ['ticket_id', 'kind', 'created_at'], unique=False)
    op.create_index('idx_events_robot_on_ticket', 'events', ['ticket_id', 'has_robot_tag', 'is_private', 'created_at'], unique=False)
    op.create_index('idx_events_ticket_created', 'events', ['ticket_id', 'created_at'], unique=False)
    op.create_table('our_posts',
    sa.Column('post_key', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('body_hash', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('created_at', db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_key')
    )
    op.create_index('idx_our_posts_ticket', 'our_posts', ['ticket_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_our_posts_ticket', table_name='our_posts')
    op.drop_table('our_posts')
    op.drop_index('idx_events_ticket_created', table_name='events')
    op.drop_index('idx_events_robot_on_ticket', table_name='events')
    op.drop_index('idx_events_kind_on_ticket', table_name='events')
    op.drop_table('events')
    op.drop_index('idx_tickets_brand_status', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('idx_locks_until', table_name='locks')
    op.drop_table('locks')
    op.drop_table('checkpoints')
    # ### end Alembic commands ###
